### ISSUE TITLE
Check git log on mac

### ISSUE THREAD

**Issue by schollz** [schollz/gojot#78]

**Comment by qwertystop** [comment]
I am uncertain whether this issue is the same as an issue I've just encountered - didn't want to duplicate. I have set up a journal on my GitHub and have accessed it from two computers - one running Mac OSX, one running Linux Mint. Initial pushes were from the Mint. Accessing it from the Mac, all of the original documents were accessible, but now that I've just tried to read the ones I created on the Mac from the Mint, they're not showing up. I can't tell whether or not they reached the GitHub repository because the timestamps are clearly messed up - some branches say they were last modified twelve years ago, and it hasn't even been two weeks since I started using gojot.

I can provide more details or test things further, if necessary. If this should be split into a separate issue I can do that - but this mentions macs specifically, so I thought it might be a known issue.
